### PR TITLE
add linkedin

### PR DESCRIPTION
**Pull request by dhia-gharsallaoui**

### CODE REVIEW

**Comment by mansoorbarri** [comment]
you can add as many links as you want as mentioned in the guide: https://mansoorbarri.com/downloads/coming-soon-hugo/#guide 

the `config.toml` file is just an example. closing pr.

**Comment by dhia-gharsallaoui** [comment]
yeah but you will not get the icon.
the PR aims to add the LinkedIn icon and I just updated the config example to say it's now available.

**Comment by mansoorbarri** [comment]
can you remove the changes in `examplesite/config.toml`?

**Comment by dhia-gharsallaoui** [comment]
yeah, I can! 
But in this case, you need to update the docs website to tell users that Linkedin is available like the others.

**Comment by mansoorbarri** [comment]
can you push white logo and remove the `config.toml` changes. I will update the documentation till then

**Comment by mansoorbarri** [comment]
documentation is updated [22e862d](https://github.com/mansoorbarri/website/commit/22e862d3a684142ea825f3058d1637f01c6851db). Approving the pr, thanks @dhia-gharsallaoui

**Pull request merged**
